### ISSUE TITLE
x3d-tidy reorders meta, component and unit statements, causing XML schema validation failures.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x3d-tidy#15] opened 2023-12-14 23:14 UTC
```bash
$ npx x3d-tidy -i examples/GrampsAnimations.x3d -o examples/GrampsAnimations.x3dj

$ grep -wiE 'component|meta|unit' examples/GrampsAnimations.x3d*
examples/GrampsAnimations.x3d:    <component level='3' name='HAnim'/>
examples/GrampsAnimations.x3d:    <unit category='length' conversionFactor='0.01' name='CENTIMETERS'/>
examples/GrampsAnimations.x3d:    <meta content='GrampsAnimations.x3d' name='filename'/>
examples/GrampsAnimations.x3d:    <meta content='2023' name='copyright'/>
examples/GrampsAnimations.x3d:    <meta content='http://www.web3D.org' name='reference'/>
examples/GrampsAnimations.x3d:    <meta content='Blender 3.6.4' name='generator'/>
examples/GrampsAnimations.x3d:    <meta content='io_scene_x3dv' name='exporter'/>
examples/GrampsAnimations.x3dj:      "meta": [
examples/GrampsAnimations.x3dj:      "component": [
examples/GrampsAnimations.x3dj:      "unit": [
```

Validation log:

    [apply] org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'component'. One of '{meta}' is expected.
    [apply]     at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    [apply]     at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
    [apply]     at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    [apply]     at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    [apply]     at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    [apply]     at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
    [apply]     at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
    [apply]     at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
    [apply]     at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
    [apply]     at org.apache.xerces.jaxp.validation.DOMValidatorHelper.beginNode(Unknown Source)
    [apply]     at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
    [apply]     at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
    [apply]     at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
    [apply]     at java.xml/javax.xml.validation.Validator.validate(Validator.java:124)
    [apply]     at Validate.main(Unknown Source)

**Comment by create3000** [comment] 2023-12-22 23:24
Duplicate of https://github.com/create3000/x3d-tidy/issues/14

**Closed by create3000** 2023-12-22 23:24 UTC

**Comment by coderextreme** [comment] 2025-08-26 02:57
Apparently, x3d-tidy is still putting component after meta. I may attempt to fix in x3DJSONLD.js.  Low priority, since this only affects VRML, until VRML becomes critical.

[JoeSkinUpdate2.zip](https://github.com/user-attachments/files/21979773/JoeSkinUpdate2.zip)

**Comment by coderextreme** [comment] 2025-08-26 03:02
Note, I'm aware of the missing joints field, and thus no animation in humanoid.
